### ANN ---> Artificial Neural Network

#### Part 1 --> Data preprocessing

In [19]:
# import libraries

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Importing the dataset

dataset=pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
X=dataset.iloc[:,3:13]
y=dataset.iloc[:,13]

In [5]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [6]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [7]:
# Create dummy variables
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X["Gender"],drop_first=True)

In [8]:
geography

      Germany  Spain
0       False  False
1       False   True
2       False  False
3       False  False
4       False   True
...       ...    ...
9995    False  False
9996    False  False
9997    False  False
9998     True  False
9999    False  False

[10000 rows x 2 columns]

In [9]:
gender

       Male
0     False
1     False
2     False
3     False
4     False
...     ...
9995   True
9996   True
9997  False
9998   True
9999  False

[10000 rows x 1 columns]

In [10]:
# Concatenate the Data Frames
X=pd.concat([X,geography,gender],axis=1)

In [11]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,France,Female,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,France,Female,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,False,True,False

In [12]:
# Drop Unnecessary columns
X=X.drop(['Geography','Gender'],axis=1)

In [13]:
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False

In [14]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Part 2 --> Now let's make ANN!

In [ ]:

# Importing the Keras libraries and packages

import keras
from keras.models import Sequential
from keras.layers import Dense
# from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [17]:
# Intialising the ANN

classifier = Sequential()

In [21]:
X.shape

(10000, 11)

In [34]:
# Adding the input layer and the first hidden layer

classifier.add(Dense(units = 10, kernel_initializer = 'he_normal',activation='relu',input_dim = 11))
# units --> number of neurons in the hidden layer
# kernel_initializer --> initialization of the weights of the neurons
# activation --> activation function used in the hidden layer
# input_dim --> number of features in the input dataset

classifier.dropout = 0.3
# dropout --> dropout rate to avoid overfitting

In [35]:
# Adding the second hidden layer
classifier.add(Dense(units = 20, kernel_initializer = 'he_normal',activation='relu'))
classifier.dropout = 0.4

In [36]:
# Adding the third hidden layer
classifier.add(Dense(units = 15, kernel_initializer = 'he_normal',activation='relu'))
classifier.dropout = 0.2

In [37]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

In [38]:
classifier.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 6)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             7 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 20)             │           220 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 15)             │           315 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,062 (4.15 KB)

 Trainable params: 734 (2.87 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 328 (1.29 KB)

In [39]:
# Complining the ANN

classifier.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# optimizer --> algorithm to find the optimal set of weights in the ANN
# loss --> loss function within the stochastic gradient algorithm 
# metrics --> criteria to evaluate the model

In [40]:
# Fitting the ANN to the Training set

model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 100)

# batch_size --> number of observations after which you want to update the weights
# nb_epochs --> number of epochs to train the model on the data

Epoch 1/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8187 - loss: 0.5316 - val_accuracy: 0.8478 - val_loss: 0.3682
Epoch 2/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8620 - loss: 0.3459 - val_accuracy: 0.8485 - val_loss: 0.3673
Epoch 3/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8706 - loss: 0.3247 - val_accuracy: 0.8508 - val_loss: 0.3642
Epoch 4/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8759 - loss: 0.3191 - val_accuracy: 0.8470 - val_loss: 0.3682
Epoch 5/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8666 - loss: 0.3290 - val_accuracy: 0.8485 - val_loss: 0.3691
Epoch 6/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8758 - loss: 0.3101 - val_accuracy: 0.8531 - val_loss: 0.3615
Epoch 7/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8817 - loss: 0.3109 - val_accuracy: 0.8512 - val_loss: 0.3624
Epoch 8/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8646 - loss: 0.3280 - val_accuracy: 0.8531 - val_loss: 0.3646
Epoch 9/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8733 - loss: 0.3231 - val_accuracy: 0.8546 - val_loss: 0.3592
Epoch 10/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8715 - loss: 0.3191 - val_accuracy: 0.8508 - val_loss: 0.3619
Epoch 11/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8696 - loss: 0.3253 - val_accuracy: 0.8501 - val_loss: 0.3632
Epoch 12/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8734 - loss: 0.3179 - val_accuracy: 0.8550 - val_loss: 0.3621
Epoch 13/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8768 - loss: 0.3075 - val_accuracy: 0.8523 - val_loss: 0.3619
Epoch 14/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8702 - loss: 0.3316 - val_accuracy: 0.8516 - val_loss: 0.3603
Epoch 15/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8713 - loss: 0.3154 - val_accuracy: 0.8546 - val_loss: 0.3585
Epoch 16/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8698 - loss: 0.3267 - val_accuracy: 0.8542 - val_loss: 0.3641
Epoch 17/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8714 - loss: 0.3110 - val_accuracy: 0.8512 - val_loss: 0.3582
Epoch 18/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8772 - loss: 0.3051 - val_accuracy: 0.8516 - val_loss: 0.3647
Epoch 19/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8726 - loss: 0.3060 - val_accuracy: 0.8508 - val_loss: 0.3586
Epoch 20/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8629 - loss: 0.3338 - val_accuracy: 0.8508 - val_loss: 0.3682
Epoch 21/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8740 - loss: 0.3202 - val_accuracy: 0.8474 - val_loss: 0.3678
Epoch 22/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8717 - loss: 0.3158 - val_accuracy: 0.8535 - val_loss: 0.3579
Epoch 23/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8676 - loss: 0.3270 - val_accuracy: 0.8512 - val_loss: 0.3584
Epoch 24/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8779 - loss: 0.3138 - val_accuracy: 0.8542 - val_loss: 0.3572
Epoch 25/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8794 - loss: 0.3095 - val_accuracy: 0.8519 - val_loss: 0.3600
Epoch 26/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8723 - loss: 0.3218 - val_accuracy: 0.8554 - val_loss: 0.3597
Epoch 27/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8705 - loss: 0.3221 - val_accuracy: 0.8546 - val_loss: 0.3599
Epoch 28/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8645 - loss: 0.3343 - val_accuracy: 0.8565 - val_loss: 0.3641
Epoch 29/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8706 - loss: 0.3224 - val_accuracy: 0.8508 - val_loss: 0.3596
Epoch 30/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8735 - loss: 0.3104 - val_accuracy: 0.8531 - val_loss: 0.3618
Epoch 31/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8609 - loss: 0.3343 - val_accuracy: 0.8523 - val_loss: 0.3674
Epoch 32/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8738 - loss: 0.3132 - val_accuracy: 0.8573 - val_loss: 0.3597
Epoch 33/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8773 - loss: 0.3104 - val_accuracy: 0.8535 - val_loss: 0.3599
Epoch 34/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8812 - loss: 0.3108 - val_accuracy: 0.8542 - val_loss: 0.3576
Epoch 35/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8693 - loss: 0.3195 - val_accuracy: 0.8519 - val_loss: 0.3623
Epoch 36/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8745 - loss: 0.3153 - val_accuracy: 0.8504 - val_loss: 0.3598
Epoch 37/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8692 - loss: 0.3198 - val_accuracy: 0.8519 - val_loss: 0.3584
Epoch 38/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8728 - loss: 0.3228 - val_accuracy: 0.8531 - val_loss: 0.3593
Epoch 39/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8686 - loss: 0.3266 - val_accuracy: 0.8482 - val_loss: 0.3612
Epoch 40/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8770 - loss: 0.3113 - val_accuracy: 0.8546 - val_loss: 0.3570
Epoch 41/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8712 - loss: 0.3175 - val_accuracy: 0.8550 - val_loss: 0.3569
Epoch 42/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8671 - loss: 0.3208 - val_accuracy: 0.8531 - val_loss: 0.3571
Epoch 43/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8724 - loss: 0.3151 - val_accuracy: 0.8565 - val_loss: 0.3581
Epoch 44/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8690 - loss: 0.3173 - val_accuracy: 0.8542 - val_loss: 0.3571
Epoch 45/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8770 - loss: 0.3126 - val_accuracy: 0.8565 - val_loss: 0.3568
Epoch 46/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8688 - loss: 0.3178 - val_accuracy: 0.8519 - val_loss: 0.3570
Epoch 47/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8783 - loss: 0.3061 - val_accuracy: 0.8550 - val_loss: 0.3622
Epoch 48/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8693 - loss: 0.3338 - val_accuracy: 0.8531 - val_loss: 0.3593
Epoch 49/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8636 - loss: 0.3297 - val_accuracy: 0.8519 - val_loss: 0.3607
Epoch 50/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8676 - loss: 0.3317 - val_accuracy: 0.8512 - val_loss: 0.3598
Epoch 51/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8695 - loss: 0.3168 - val_accuracy: 0.8523 - val_loss: 0.3637
Epoch 52/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8730 - loss: 0.3117 - val_accuracy: 0.8523 - val_loss: 0.3593
Epoch 53/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8629 - loss: 0.3295 - val_accuracy: 0.8554 - val_loss: 0.3610
Epoch 54/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8713 - loss: 0.3133 - val_accuracy: 0.8554 - val_loss: 0.3591
Epoch 55/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8672 - loss: 0.3175 - val_accuracy: 0.8523 - val_loss: 0.3620
Epoch 56/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8724 - loss: 0.3154 - val_accuracy: 0.8546 - val_loss: 0.3585
Epoch 57/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8771 - loss: 0.3143 - val_accuracy: 0.8535 - val_loss: 0.3627
Epoch 58/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8646 - loss: 0.3245 - val_accuracy: 0.8527 - val_loss: 0.3580
Epoch 59/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8700 - loss: 0.3268 - val_accuracy: 0.8501 - val_loss: 0.3605
Epoch 60/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8757 - loss: 0.3070 - val_accuracy: 0.8512 - val_loss: 0.3605
Epoch 61/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8827 - loss: 0.3041 - val_accuracy: 0.8557 - val_loss: 0.3587
Epoch 62/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8723 - loss: 0.3091 - val_accuracy: 0.8523 - val_loss: 0.3608
Epoch 63/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8711 - loss: 0.3204 - val_accuracy: 0.8565 - val_loss: 0.3571
Epoch 64/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8726 - loss: 0.3185 - val_accuracy: 0.8523 - val_loss: 0.3595
Epoch 65/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8801 - loss: 0.3095 - val_accuracy: 0.8474 - val_loss: 0.3735
Epoch 66/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8689 - loss: 0.3157 - val_accuracy: 0.8538 - val_loss: 0.3593
Epoch 67/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8661 - loss: 0.3244 - val_accuracy: 0.8542 - val_loss: 0.3605
Epoch 68/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8780 - loss: 0.3222 - val_accuracy: 0.8531 - val_loss: 0.3637
Epoch 69/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8718 - loss: 0.3192 - val_accuracy: 0.8554 - val_loss: 0.3594
Epoch 70/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8638 - loss: 0.3297 - val_accuracy: 0.8531 - val_loss: 0.3597
Epoch 71/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8715 - loss: 0.3160 - val_accuracy: 0.8519 - val_loss: 0.3646
Epoch 72/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8783 - loss: 0.3084 - val_accuracy: 0.8519 - val_loss: 0.3595
Epoch 73/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8735 - loss: 0.3134 - val_accuracy: 0.8550 - val_loss: 0.3597
Epoch 74/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8719 - loss: 0.3132 - val_accuracy: 0.8519 - val_loss: 0.3648
Epoch 75/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8751 - loss: 0.3198 - val_accuracy: 0.8519 - val_loss: 0.3634
Epoch 76/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8647 - loss: 0.3194 - val_accuracy: 0.8531 - val_loss: 0.3630
Epoch 77/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8713 - loss: 0.3155 - val_accuracy: 0.8542 - val_loss: 0.3585
Epoch 78/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8659 - loss: 0.3236 - val_accuracy: 0.8531 - val_loss: 0.3612
Epoch 79/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8707 - loss: 0.3153 - val_accuracy: 0.8531 - val_loss: 0.3593
Epoch 80/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8701 - loss: 0.3233 - val_accuracy: 0.8535 - val_loss: 0.3588
Epoch 81/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8676 - loss: 0.3243 - val_accuracy: 0.8512 - val_loss: 0.3598
Epoch 82/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8708 - loss: 0.3253 - val_accuracy: 0.8546 - val_loss: 0.3610
Epoch 83/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8780 - loss: 0.3096 - val_accuracy: 0.8516 - val_loss: 0.3599
Epoch 84/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8751 - loss: 0.3139 - val_accuracy: 0.8561 - val_loss: 0.3583
Epoch 85/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8706 - loss: 0.3141 - val_accuracy: 0.8531 - val_loss: 0.3592
Epoch 86/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8590 - loss: 0.3357 - val_accuracy: 0.8542 - val_loss: 0.3609
Epoch 87/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8632 - loss: 0.3318 - val_accuracy: 0.8531 - val_loss: 0.3624
Epoch 88/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8670 - loss: 0.3242 - val_accuracy: 0.8546 - val_loss: 0.3583
Epoch 89/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8651 - loss: 0.3273 - val_accuracy: 0.8535 - val_loss: 0.3575
Epoch 90/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8591 - loss: 0.3273 - val_accuracy: 0.8546 - val_loss: 0.3611
Epoch 91/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8716 - loss: 0.3195 - val_accuracy: 0.8542 - val_loss: 0.3581
Epoch 92/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8646 - loss: 0.3323 - val_accuracy: 0.8542 - val_loss: 0.3606
Epoch 93/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8641 - loss: 0.3363 - val_accuracy: 0.8557 - val_loss: 0.3595
Epoch 94/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8775 - loss: 0.3028 - val_accuracy: 0.8531 - val_loss: 0.3581
Epoch 95/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8745 - loss: 0.3136 - val_accuracy: 0.8497 - val_loss: 0.3706
Epoch 96/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8687 - loss: 0.3252 - val_accuracy: 0.8546 - val_loss: 0.3636
Epoch 97/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8755 - loss: 0.3110 - val_accuracy: 0.8523 - val_loss: 0.3590
Epoch 98/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8767 - loss: 0.3098 - val_accuracy: 0.8550 - val_loss: 0.3596
Epoch 99/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8797 - loss: 0.3076 - val_accuracy: 0.8523 - val_loss: 0.3653
Epoch 100/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8817 - loss: 0.3027 - val_accuracy: 0.8569 - val_loss: 0.3601

In [41]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [42]:
# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1487,  108],
       [ 190,  215]], dtype=int64)

In [43]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score

0.851